### ISSUE TITLE
Ref's Secure container "Theta"

### ISSUE THREAD

**Issue by SGZ-Creations** [harmerTM/ConfigurableInventories#4]
​Hey any chance in adding the Theta Secure Case to the list?
![Theta Secure Container](https://github.com/user-attachments/assets/b180b25d-49cd-4e3d-8e6c-3f27314ba7af)
![casecode](https://github.com/user-attachments/assets/2bd87572-2e7c-479d-aa2c-3471de8a25d3)

**Comment by harmerTM** [comment]
[#2 ](https://github.com/harmerTM/ConfigurableInventories/pull/2)
Added in pull request.
